function coarse_output = coarsenCubeSize2(input)

coarse_output = zeros(size(input)./2);

for i2 = 1:size(coarse_output,1)
    for j2 = 1:size(coarse_output,2)
        for k2 = 1:size(coarse_output,3)
            i = 2*i2-1; j = 2*j2-1; k = 2*k2-1; % Centre of cube to coarsen (cube size 2x2x2)
            coarse_output(i2,j2,k2) =...
                (input(i,j,k) +...
                input(i,j+1,k) +...
                input(i,j,k+1) +...
                input(i,j+1,k+1) +...
                input(i+1,j,k) +...
                input(i+1,j+1,k) +...
                input(i+1,j,k+1) +...
                input(i+1,j+1,k+1) )/8;
        end
    end
end


end